name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 . || true

  build:
    runs-on: ubuntu-latest
    needs: lint

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/fastapi-app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: List Docker images
        run: docker images

  health-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install uvicorn[standard] fastapi

      - name: Start API in background
        run: |
          nohup uvicorn api.api_server:app --host 127.0.0.1 --port 8000 &

      - name: Wait for API to start
        run: sleep 5

      - name: Test root endpoint
        run: |
          curl --fail http://127.0.0.1:8000/ || (echo "API não subiu" && exit 1)
