name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 .

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t my-fastapi-app .

      - name: List Docker images
        run: docker images
        
  health-check:
    runs-on: ubuntu-latest
    needs: build  # espera o build passar
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install uvicorn[standard] fastapi

      - name: Start API in background
        run: |
          nohup uvicorn api.api_server:app --host 127.0.0.1 --port 8000 &

      - name: Wait for API to start
        run: sleep 5

      - name: Test root endpoint
        run: |
          curl --fail http://127.0.0.1:8000/ || (echo "API não subiu" && exit 1)
